"""
core/deliverable_verifier.py — Output Deliverable Integrity & Quality Verifier.

Verifies code and document deliverables generated by autonomous agents before task completion:
- HTML/CSS: Validates tag balance, viewport meta, structure, and basic syntax.
- Python/JS: Checks for non-empty AST well-formedness / compile sanity.
- Markdown/Docs: Checks minimum length and structural headers.
"""

from __future__ import annotations

import ast
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple


@dataclass
class VerificationResult:
    valid: bool
    deliverable_type: str
    target_path: Optional[str] = None
    issues: List[str] = None
    metrics: Dict[str, any] = None

    def __post_init__(self):
        if self.issues is None:
            self.issues = []
        if self.metrics is None:
            self.metrics = {}


def verify_deliverable(
    task_type: str,
    path: Optional[str] = None,
    content: Optional[str] = None,
) -> VerificationResult:
    """
    Verify integrity and well-formedness of a deliverable file or content string.
    Supported task_types: 'html', 'python', 'javascript', 'markdown', 'document', 'auto'.
    """
    raw_text = content
    target_path = path

    if path and not raw_text:
        p = Path(path)
        if not p.exists():
            return VerificationResult(
                valid=False,
                deliverable_type=task_type,
                target_path=path,
                issues=[f"Deliverable file does not exist: {path}"],
            )
        try:
            raw_text = p.read_text(encoding="utf-8", errors="replace")
        except Exception as e:
            return VerificationResult(
                valid=False,
                deliverable_type=task_type,
                target_path=path,
                issues=[f"Could not read deliverable file: {e}"],
            )

    if not raw_text or not raw_text.strip():
        return VerificationResult(
            valid=False,
            deliverable_type=task_type,
            target_path=path,
            issues=["Deliverable content is empty or blank."],
        )

    t = (task_type or "auto").lower().strip()
    if t == "auto":
        if path:
            ext = Path(path).suffix.lower()
            if ext in (".html", ".htm"):
                t = "html"
            elif ext == ".py":
                t = "python"
            elif ext in (".js", ".mjs", ".ts"):
                t = "javascript"
            elif ext in (".md", ".txt"):
                t = "markdown"
            else:
                t = "document"
        else:
            if "<!doctype html" in raw_text.lower() or "<html" in raw_text.lower():
                t = "html"
            elif "def " in raw_text or "import " in raw_text:
                t = "python"
            else:
                t = "document"

    if t in ("html", "web", "landing_page"):
        return _verify_html(raw_text, target_path)
    elif t in ("python", "py"):
        return _verify_python(raw_text, target_path)
    elif t in ("javascript", "js", "ts"):
        return _verify_javascript(raw_text, target_path)
    else:
        return _verify_document(raw_text, target_path)


def _verify_html(content: str, path: Optional[str]) -> VerificationResult:
    issues = []
    low = content.lower()
    
    if "<!doctype html" not in low and "<html" not in low:
        issues.append("Missing <!DOCTYPE html> or <html> root tag.")
    
    # Check essential tags
    if "<head" not in low:
        issues.append("Missing <head> section.")
    if "<body" not in low:
        issues.append("Missing <body> section.")
        
    # Check viewport for responsive mobile design
    if "name=\"viewport\"" not in low and "name='viewport'" not in low and 'name="viewport"' not in low:
        issues.append("Missing mobile responsive viewport meta tag (<meta name=\"viewport\" ...>).")

    # Balanced tag sanity check for major structural containers
    for tag in ("html", "head", "body", "main"):
        open_count = len(re.findall(rf"<{tag}[\s>]", low))
        close_count = len(re.findall(rf"</{tag}>", low))
        if open_count != close_count and open_count > 0:
            issues.append(f"Unbalanced <{tag}> tag: {open_count} opened vs {close_count} closed.")

    valid = len(issues) == 0
    return VerificationResult(
        valid=valid,
        deliverable_type="html",
        target_path=path,
        issues=issues,
        metrics={"char_count": len(content), "lines": len(content.splitlines())},
    )


def _verify_python(content: str, path: Optional[str]) -> VerificationResult:
    issues = []
    try:
        ast.parse(content)
    except SyntaxError as e:
        issues.append(f"Python SyntaxError at line {e.lineno}: {e.msg}")
    except Exception as e:
        issues.append(f"AST parse error: {e}")

    valid = len(issues) == 0
    return VerificationResult(
        valid=valid,
        deliverable_type="python",
        target_path=path,
        issues=issues,
        metrics={"char_count": len(content), "lines": len(content.splitlines())},
    )


def _verify_javascript(content: str, path: Optional[str]) -> VerificationResult:
    issues = []
    # Check brace balance
    open_curly = content.count("{")
    close_curly = content.count("}")
    if open_curly != close_curly:
        issues.append(f"Unbalanced curly braces: {open_curly} '{{' vs {close_curly} '}}'")

    open_paren = content.count("(")
    close_paren = content.count(")")
    if open_paren != close_paren:
        issues.append(f"Unbalanced parentheses: {open_paren} '(' vs {close_paren} ')'")

    valid = len(issues) == 0
    return VerificationResult(
        valid=valid,
        deliverable_type="javascript",
        target_path=path,
        issues=issues,
        metrics={"char_count": len(content), "lines": len(content.splitlines())},
    )


def _verify_document(content: str, path: Optional[str]) -> VerificationResult:
    issues = []
    if len(content.strip()) < 20:
        issues.append("Document deliverable is suspiciously brief (<20 characters).")

    valid = len(issues) == 0
    return VerificationResult(
        valid=valid,
        deliverable_type="document",
        target_path=path,
        issues=issues,
        metrics={"char_count": len(content), "lines": len(content.splitlines())},
    )
