import pathlib, re
h = pathlib.Path("frontend/index.html").read_text(encoding="utf-8")
print("audio-input-select id  :", h.count('id="audio-input-select"'))
print("audio-output-select id :", h.count('id="audio-output-select"'))
print("window.saveAudioDevices  :", h.count("window.saveAudioDevices"))
print("window.requestAudioDevices:", h.count("window.requestAudioDevices"))
print("audio_devices_updated listener:", h.count("socket.on('audio_devices_updated'"))
print("hardcoded 'USB PnP' remaining :", h.count("USB PnP Sound Device"))
print("hardcoded '463ms' remaining   :", h.count("463ms"))
blocks = re.findall(r'<script[^>]*type="module"[^>]*>(.*?)</script>', h, re.S)
mod = next(b for b in blocks if "socket.js" in b)
pathlib.Path("scratch/frontend_module.mjs").write_text(mod, encoding="utf-8")
print("extracted module script chars:", len(mod))
